import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import SideNavigation from "../components/side-navigation";

const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={karla.className}>
                <SideNavigation />
                <div className="h-full flex flex-col flex-1">{children}</div>
            </body>
        </html>
    );
}
